'use strict';
const rooms={living:{title:'Гостиная',image:'assets/living.png',description:'Место для долгих разговоров. Низкая мебель сохраняет объём комнаты, а дневной свет свободно проходит в глубину квартиры.'},kitchen:{title:'Кухня',image:'assets/kitchen.png',description:'Большой стол объединяет кухню и общую зону. Деревянные фасады скрывают хранение, а каменный остров становится центром ежедневных ритуалов.'},bedroom:{title:'Спальня',image:'assets/bedroom.png',description:'Самая тихая часть квартиры. Мягкий текстиль, рассеянный свет и минимум предметов помогают переключиться с городского ритма на свой.'}};
const portfolio={forest:{title:'Сосновый склон',meta:'Загородный дом · 240 м²',image:'assets/forest-house.png',detail:'assets/forest-detail.png',alt:'Общая комната загородного дома с видом на сосновый лес',detailAlt:'Другой ракурс того же загородного дома: столовая и лесное остекление',story:'Концепт загородного дома для семьи, которая проводит вместе выходные и часто принимает гостей. Главная комната обращена к лесу; большой стол находится рядом с очагом.',decision:'Высокое остекление даёт природному свету пройти через общую зону. Тёплое дерево объединяет потолок и встроенное хранение, камень собирает композицию вокруг очага.'},color:{title:'Город в цвете',meta:'Квартира · 112 м²',image:'assets/color-apartment.png',detail:'assets/color-detail.png',alt:'Яркая квартира коллекционера с сине-зелёной кухней и терракотовой зоной отдыха',detailAlt:'Второй вид квартиры коллекционера с тёмными стенами и искусством',story:'Концепт квартиры для человека, который собирает искусство и любит принимать друзей. Пространство строится как последовательность комнат, где у каждого произведения есть своё место.',decision:'Тёмная кухня становится фоном для насыщенных предметов, а терракотовая обивка отмечает место для долгого ужина. Переходы между помещениями дают нужную паузу взгляду.'},townhouse:{title:'Дом на Неве',meta:'Городской дом · 185 м²',image:'assets/bright-townhouse.png',detail:'assets/townhouse-detail.png',alt:'Светлый двухуровневый дом с лестницей, высоким окном и голубым диваном',detailAlt:'Вид со второго уровня на светлую гостиную с голубым диваном',story:'Концепт городского дома для семьи с детьми. Общая комната открыта на два уровня, чтобы дневной свет доходил до лестницы и объединял помещения.',decision:'Светлая отделка поддерживает высоту пространства, а мебель насыщенного цвета помогает человеку почувствовать масштаб большой комнаты. Тихие зоны остаются за пределами общего маршрута.'}};
const roomKeys=Object.keys(rooms);let currentRoom='living',galleryRoom='living';
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const still=new URLSearchParams(location.search).has('still');if(still)document.documentElement.classList.add('still');
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.navigation');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Открыть меню')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню')});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus()}});
matchMedia('(min-width:701px)').addEventListener('change',closeMenu);
function changeRoom(key){if(!rooms[key])return;currentRoom=key;const r=rooms[key],img=document.querySelector('#room-image');img.src=r.image;img.alt=r.title+', авторский интерьерный концепт';document.querySelector('#room-title').textContent=r.title;document.querySelector('#room-description').textContent=r.description;document.querySelector('.zoom-trigger').setAttribute('aria-label','Рассмотреть '+r.title.toLowerCase()+' на весь экран');document.querySelectorAll('[data-room]').forEach(el=>{const active=el.dataset.room===key;el.setAttribute('aria-pressed',String(active));el.classList.toggle('active',active)});if(!reducedMotion.matches&&!still)img.animate([{opacity:.55,transform:'scale(1.025)'},{opacity:1,transform:'scale(1)'}],{duration:450,easing:'cubic-bezier(.22,1,.36,1)'})}
document.querySelectorAll('[data-room]').forEach(el=>{el.addEventListener('click',()=>changeRoom(el.dataset.room));if(el.tagName.toLowerCase()==='g')el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();changeRoom(el.dataset.room)}})});
const materials={wood:{name:'Тёмный орех',copy:'Глубокий оттенок связывает мебель и кухню. Матовая поверхность подчёркивает естественный рисунок волокон.',caption:'Орех · естественная текстура'},stone:{name:'Светлый травертин',copy:'Пористый камень добавляет рельеф и живой рисунок. Скульптурная форма столика делает материал самостоятельной частью композиции.',caption:'Травертин · природный рельеф'},linen:{name:'Фактурный лён',copy:'Мягкая обивка рассеивает свет и уравновешивает строгую геометрию мебели. Нейтральный оттенок объединяет разные фактуры.',caption:'Лён · мягкое прикосновение'}};
document.querySelectorAll('[data-material]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.material,m=materials[key];document.querySelectorAll('[data-material]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));document.querySelector('#material-name').textContent=m.name;document.querySelector('#material-copy').textContent=m.copy;document.querySelector('#material-caption').textContent=m.caption;const p=document.querySelector('#material-photo');p.className='material-photo '+key;p.setAttribute('aria-label',m.name+' в интерьере гостиной')}));
const dialog=document.querySelector('#gallery');function renderGallery(key){galleryRoom=key;document.querySelector('#gallery-title').textContent=rooms[key].title;document.querySelector('#gallery-image').src=rooms[key].image;document.querySelector('#gallery-image').alt=rooms[key].title+', полный кадр интерьера';document.querySelector('#gallery-count').textContent=(roomKeys.indexOf(key)+1)+' / '+roomKeys.length}
function openGallery(key){renderGallery(key);dialog.showModal();document.body.classList.add('modal-open')}
document.querySelector('.zoom-trigger').addEventListener('click',()=>openGallery(currentRoom));document.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>openGallery(b.dataset.gallery)));
document.querySelector('.gallery-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close()});
const workDialog=document.querySelector('#work-dialog');document.querySelectorAll('[data-work]').forEach(trigger=>trigger.addEventListener('click',()=>{const project=portfolio[trigger.dataset.work];document.querySelector('#work-dialog-image').src=project.image;document.querySelector('#work-dialog-image').alt=project.alt;document.querySelector('#work-dialog-detail').src=project.detail;document.querySelector('#work-dialog-detail').alt=project.detailAlt;document.querySelector('#work-dialog-meta').textContent=project.meta;document.querySelector('#work-dialog-title').textContent=project.title;document.querySelector('#work-dialog-story').textContent=project.story;document.querySelector('#work-dialog-decision').textContent=project.decision;workDialog.showModal();document.body.classList.add('modal-open')}));
document.querySelector('.work-dialog-close').addEventListener('click',()=>workDialog.close());workDialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));workDialog.addEventListener('click',e=>{const r=workDialog.getBoundingClientRect();if(e.target===workDialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))workDialog.close()});document.querySelector('.work-dialog-cta').addEventListener('click',()=>workDialog.close());
function moveGallery(delta){renderGallery(roomKeys[(roomKeys.indexOf(galleryRoom)+delta+roomKeys.length)%roomKeys.length])}
document.querySelector('#gallery-prev').addEventListener('click',()=>moveGallery(-1));document.querySelector('#gallery-next').addEventListener('click',()=>moveGallery(1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();moveGallery(-1)}if(e.key==='ArrowRight'){e.preventDefault();moveGallery(1)}});
const form=document.querySelector('#brief-form');form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),name=String(data.get('name')).trim();if(!name){form.elements.name.setCustomValidity('Укажите ваше имя');form.elements.name.reportValidity();return}const brief=['SEREIN / БРИФ НА ДИЗАЙН ИНТЕРЬЕРА','Концептуальная работа Stack','',`Имя: ${name}`,`Почта: ${data.get('email')}`,`Объект: ${data.get('type')}`,`Площадь: ${data.get('area')} м²`,`Начало: ${data.get('timing')}`,`Пожелания: ${String(data.get('wishes')).trim()||'Не указаны'}`,'','Этот файл сохранён локально. Данные никуда не отправлены.'].join('\n');const blob=new Blob(['\uFEFF',brief],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='serein-brief.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);document.querySelector('#form-status').textContent='Бриф подготовлен. Скачивание началось; данные остались на вашем устройстве.'});form.elements.name.addEventListener('input',()=>form.elements.name.setCustomValidity(''));
if(!still){gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.from('.title-line',{y:35,opacity:0,duration:1.1,stagger:.14,ease:'power3.out'});gsap.from('.hero-figure',{y:28,opacity:0,duration:1.2,delay:.15,ease:'power3.out'});gsap.to('.hero-image',{scale:1.08,ease:'none',scrollTrigger:{trigger:'.hero-image-wrap',start:'top bottom',end:'bottom top',scrub:1}});gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{y:35,opacity:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 91%',once:true}}));return()=>{}})}
if(still){const at=new URLSearchParams(location.search).get('at');if(at)window.addEventListener('load',()=>document.getElementById(at)?.scrollIntoView())}
